<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CODEC [
   <!ELEMENT CODEC (EPSG+)>
   <!ELEMENT EPSG (#PCDATA)>
   <!ATTLIST EPSG id ID #REQUIRED>      
]>
<CODEC>
<!-- # Unknown datum based upon the Airy 1830 ellipsoid -->
<EPSG id="4001"> +proj=longlat +ellps=airy +no_defs  </EPSG>
<!-- # Unknown datum based upon the Airy Modified 1849 ellipsoid -->
<EPSG id="4002"> +proj=longlat +a=6377340.189 +b=6356034.447938534 +no_defs  </EPSG>
<!-- # Unknown datum based upon the Australian National Spheroid -->
<EPSG id="4003"> +proj=longlat +ellps=aust_SA +no_defs  </EPSG>
<!-- # Unknown datum based upon the Bessel 1841 ellipsoid -->
<EPSG id="4004"> +proj=longlat +ellps=bessel +no_defs  </EPSG>
<!-- # Unknown datum based upon the Bessel Modified ellipsoid -->
<EPSG id="4005"> +proj=longlat +a=6377492.018 +b=6356173.508712696 +no_defs  </EPSG>
<!-- # Unknown datum based upon the Bessel Namibia ellipsoid -->
<EPSG id="4006"> +proj=longlat +ellps=bess_nam +no_defs  </EPSG>
<!-- # Unknown datum based upon the Clarke 1858 ellipsoid -->
<EPSG id="4007"> +proj=longlat +a=6378293.63683822 +b=6356617.979337744 +no_defs  </EPSG>
<!-- # Unknown datum based upon the Clarke 1866 ellipsoid -->
<EPSG id="4008"> +proj=longlat +ellps=clrk66 +no_defs  </EPSG>
<!-- # Unknown datum based upon the Clarke 1866 Michigan ellipsoid -->
<EPSG id="4009"> +proj=longlat +a=6378450.047548896 +b=6356826.621488444 +no_defs  </EPSG>
<!-- # Unknown datum based upon the Clarke 1880 (Benoit) ellipsoid -->
<EPSG id="4010"> +proj=longlat +a=6378300.789 +b=6356566.435 +no_defs  </EPSG>
<!-- # Unknown datum based upon the Clarke 1880 (IGN) ellipsoid -->
<EPSG id="4011"> +proj=longlat +a=6378249.2 +b=6356515 +no_defs  </EPSG>
<!-- # Unknown datum based upon the Clarke 1880 (RGS) ellipsoid -->
<EPSG id="4012"> +proj=longlat +ellps=clrk80 +no_defs  </EPSG>
<!-- # Unknown datum based upon the Clarke 1880 (Arc) ellipsoid -->
<EPSG id="4013"> +proj=longlat +a=6378249.145 +b=6356514.966398753 +no_defs  </EPSG>
<!-- # Unknown datum based upon the Clarke 1880 (SGA 1922) ellipsoid -->
<EPSG id="4014"> +proj=longlat +a=6378249.2 +b=6356514.996941779 +no_defs  </EPSG>
<!-- # Unknown datum based upon the Everest 1830 (1937 Adjustment) ellipsoid -->
<EPSG id="4015"> +proj=longlat +a=6377276.345 +b=6356075.413140239 +no_defs  </EPSG>
<!-- # Unknown datum based upon the Everest 1830 (1967 Definition) ellipsoid -->
<EPSG id="4016"> +proj=longlat +ellps=evrstSS +no_defs  </EPSG>
<!-- # Unknown datum based upon the Everest 1830 Modified ellipsoid -->
<EPSG id="4018"> +proj=longlat +a=6377304.063 +b=6356103.038993155 +no_defs  </EPSG>
<!-- # Unknown datum based upon the GRS 1980 ellipsoid -->
<EPSG id="4019"> +proj=longlat +ellps=GRS80 +no_defs  </EPSG>
<!-- # Unknown datum based upon the Helmert 1906 ellipsoid -->
<EPSG id="4020"> +proj=longlat +ellps=helmert +no_defs  </EPSG>
<!-- # Unknown datum based upon the Indonesian National Spheroid -->
<EPSG id="4021"> +proj=longlat +a=6378160 +b=6356774.50408554 +no_defs  </EPSG>
<!-- # Unknown datum based upon the International 1924 ellipsoid -->
<EPSG id="4022"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # Unknown datum based upon the Krassowsky 1940 ellipsoid -->
<EPSG id="4024"> +proj=longlat +ellps=krass +no_defs  </EPSG>
<!-- # Unknown datum based upon the NWL 9D ellipsoid -->
<EPSG id="4025"> +proj=longlat +ellps=WGS66 +no_defs  </EPSG>
<!-- # Unknown datum based upon the Plessis 1817 ellipsoid -->
<EPSG id="4027"> +proj=longlat +a=6376523 +b=6355862.933255573 +no_defs  </EPSG>
<!-- # Unknown datum based upon the Struve 1860 ellipsoid -->
<EPSG id="4028"> +proj=longlat +a=6378298.3 +b=6356657.142669562 +no_defs  </EPSG>
<!-- # Unknown datum based upon the War Office ellipsoid -->
<EPSG id="4029"> +proj=longlat +a=6378300 +b=6356751.689189189 +no_defs  </EPSG>
<!-- # Unknown datum based upon the WGS 84 ellipsoid -->
<EPSG id="4030"> +proj=longlat +ellps=WGS84 +no_defs  </EPSG>
<!-- # Unknown datum based upon the GEM 10C ellipsoid -->
<EPSG id="4031"> +proj=longlat +ellps=WGS84 +no_defs  </EPSG>
<!-- # Unknown datum based upon the OSU86F ellipsoid -->
<EPSG id="4032"> +proj=longlat +a=6378136.2 +b=6356751.516927429 +no_defs  </EPSG>
<!-- # Unknown datum based upon the OSU91A ellipsoid -->
<EPSG id="4033"> +proj=longlat +a=6378136.3 +b=6356751.616592146 +no_defs  </EPSG>
<!-- # Unknown datum based upon the Clarke 1880 ellipsoid -->
<EPSG id="4034"> +proj=longlat +ellps=clrk80 +no_defs  </EPSG>
<!-- # Unknown datum based upon the Authalic Sphere -->
<EPSG id="4035"> +proj=longlat +a=6371000 +b=6371000 +no_defs  </EPSG>
<!-- # Unknown datum based upon the GRS 1967 ellipsoid -->
<EPSG id="4036"> +proj=longlat +ellps=GRS67 +no_defs  </EPSG>
<!-- # Unknown datum based upon the Average Terrestrial System 1977 ellipsoid -->
<EPSG id="4041"> +proj=longlat +a=6378135 +b=6356750.304921594 +no_defs  </EPSG>
<!-- # Unknown datum based upon the Everest (1830 Definition) ellipsoid -->
<EPSG id="4042"> +proj=longlat +a=6377299.36559538 +b=6356098.357204817 +no_defs  </EPSG>
<!-- # Unknown datum based upon the WGS 72 ellipsoid -->
<EPSG id="4043"> +proj=longlat +ellps=WGS72 +no_defs  </EPSG>
<!-- # Unknown datum based upon the Everest 1830 (1962 Definition) ellipsoid -->
<EPSG id="4044"> +proj=longlat +a=6377301.243 +b=6356100.230165385 +no_defs  </EPSG>
<!-- # Unknown datum based upon the Everest 1830 (1975 Definition) ellipsoid -->
<EPSG id="4045"> +proj=longlat +a=6377299.151 +b=6356098.145120132 +no_defs  </EPSG>
<!-- # Unspecified datum based upon the GRS 1980 Authalic Sphere -->
<EPSG id="4047"> +proj=longlat +a=6370997 +b=6370997 +no_defs  </EPSG>
<!-- # Greek -->
<EPSG id="4120"> +proj=longlat +ellps=bessel +no_defs  </EPSG>
<!-- # GGRS87 -->
<EPSG id="4121"> +proj=longlat +ellps=GRS80 +towgs84=-199.87,74.79,246.62,0,0,0,0 +no_defs  </EPSG>
<!-- # ATS77 -->
<EPSG id="4122"> +proj=longlat +a=6378135 +b=6356750.304921594 +no_defs  </EPSG>
<!-- # KKJ -->
<EPSG id="4123"> +proj=longlat +ellps=intl +towgs84=-90.7,-106.1,-119.2,4.09,0.218,-1.05,1.37 +no_defs  </EPSG>
<!-- # RT90 -->
<EPSG id="4124"> +proj=longlat +ellps=bessel +no_defs  </EPSG>
<!-- # Samboja -->
<EPSG id="4125"> +proj=longlat +ellps=bessel +towgs84=-404.78,685.68,45.47,0,0,0,0 +no_defs  </EPSG>
<!-- # LKS94 (ETRS89) -->
<EPSG id="4126"> +proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs  </EPSG>
<!-- # Tete -->
<EPSG id="4127"> +proj=longlat +ellps=clrk66 +no_defs  </EPSG>
<!-- # Madzansua -->
<EPSG id="4128"> +proj=longlat +ellps=clrk66 +no_defs  </EPSG>
<!-- # Observatario -->
<EPSG id="4129"> +proj=longlat +ellps=clrk66 +no_defs  </EPSG>
<!-- # Moznet -->
<EPSG id="4130"> +proj=longlat +ellps=WGS84 +towgs84=0,0,0,-0,-0,-0,0 +no_defs  </EPSG>
<!-- # Indian 1960 -->
<EPSG id="4131"> +proj=longlat +a=6377276.345 +b=6356075.413140239 +no_defs  </EPSG>
<!-- # FD58 -->
<EPSG id="4132"> +proj=longlat +ellps=clrk80 +no_defs  </EPSG>
<!-- # EST92 -->
<EPSG id="4133"> +proj=longlat +ellps=GRS80 +towgs84=0.055,-0.541,-0.185,0.0183,-0.0003,-0.007,-0.014 +no_defs  </EPSG>
<!-- # PDO Survey Datum 1993 -->
<EPSG id="4134"> +proj=longlat +ellps=clrk80 +no_defs  </EPSG>
<!-- # Old Hawaiian -->
<EPSG id="4135"> +proj=longlat +ellps=clrk66 +no_defs  </EPSG>
<!-- # St. Lawrence Island -->
<EPSG id="4136"> +proj=longlat +ellps=clrk66 +no_defs  </EPSG>
<!-- # St. Paul Island -->
<EPSG id="4137"> +proj=longlat +ellps=clrk66 +no_defs  </EPSG>
<!-- # St. George Island -->
<EPSG id="4138"> +proj=longlat +ellps=clrk66 +no_defs  </EPSG>
<!-- # Puerto Rico -->
<EPSG id="4139"> +proj=longlat +ellps=clrk66 +towgs84=11,72,-101,0,0,0,0 +no_defs  </EPSG>
<!-- # NAD83(CSRS98) -->
<EPSG id="4140"> +proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs  </EPSG>
<!-- # Israel -->
<EPSG id="4141"> +proj=longlat +ellps=GRS80 +no_defs  </EPSG>
<!-- # Locodjo 1965 -->
<EPSG id="4142"> +proj=longlat +ellps=clrk80 +towgs84=-125,53,467,0,0,0,0 +no_defs  </EPSG>
<!-- # Abidjan 1987 -->
<EPSG id="4143"> +proj=longlat +ellps=clrk80 +towgs84=-124.76,53,466.79,0,0,0,0 +no_defs  </EPSG>
<!-- # Kalianpur 1937 -->
<EPSG id="4144"> +proj=longlat +a=6377276.345 +b=6356075.413140239 +no_defs  </EPSG>
<!-- # Kalianpur 1962 -->
<EPSG id="4145"> +proj=longlat +a=6377301.243 +b=6356100.230165385 +towgs84=283,682,231,0,0,0,0 +no_defs  </EPSG>
<!-- # Kalianpur 1975 -->
<EPSG id="4146"> +proj=longlat +a=6377299.151 +b=6356098.145120132 +towgs84=295,736,257,0,0,0,0 +no_defs  </EPSG>
<!-- # Hanoi 1972 -->
<EPSG id="4147"> +proj=longlat +ellps=krass +towgs84=-17.51,-108.32,-62.39,0,0,0,0 +no_defs  </EPSG>
<!-- # Hartebeesthoek94 -->
<EPSG id="4148"> +proj=longlat +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +no_defs  </EPSG>
<!-- # CH1903 -->
<EPSG id="4149"> +proj=longlat +ellps=bessel +no_defs  </EPSG>
<!-- # CH1903+ -->
<EPSG id="4150"> +proj=longlat +ellps=bessel +towgs84=674.374,15.056,405.346,0,0,0,0 +no_defs  </EPSG>
<!-- # CHTRF95 -->
<EPSG id="4151"> +proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs  </EPSG>
<!-- # NAD83(HARN) -->
<EPSG id="4152"> +proj=longlat +ellps=GRS80 +no_defs  </EPSG>
<!-- # Rassadiran -->
<EPSG id="4153"> +proj=longlat +ellps=intl +towgs84=-133.63,-157.5,-158.62,0,0,0,0 +no_defs  </EPSG>
<!-- # ED50(ED77) -->
<EPSG id="4154"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # Dabola 1981 -->
<EPSG id="4155"> +proj=longlat +a=6378249.2 +b=6356515 +towgs84=-83,37,124,0,0,0,0 +no_defs  </EPSG>
<!-- # S-JTSK -->
<EPSG id="4156"> +proj=longlat +ellps=bessel +no_defs  </EPSG>
<!-- # Mount Dillon -->
<EPSG id="4157"> +proj=longlat +a=6378293.63683822 +b=6356617.979337744 +no_defs  </EPSG>
<!-- # Naparima 1955 -->
<EPSG id="4158"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # ELD79 -->
<EPSG id="4159"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # Chos Malal 1914 -->
<EPSG id="4160"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # Pampa del Castillo -->
<EPSG id="4161"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # Korean 1985 -->
<EPSG id="4162"> +proj=longlat +ellps=bessel +no_defs  </EPSG>
<!-- # Yemen NGN96 -->
<EPSG id="4163"> +proj=longlat +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +no_defs  </EPSG>
<!-- # South Yemen -->
<EPSG id="4164"> +proj=longlat +ellps=krass +towgs84=-76,-138,67,0,0,0,0 +no_defs  </EPSG>
<!-- # Bissau -->
<EPSG id="4165"> +proj=longlat +ellps=intl +towgs84=-173,253,27,0,0,0,0 +no_defs  </EPSG>
<!-- # Korean 1995 -->
<EPSG id="4166"> +proj=longlat +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +no_defs  </EPSG>
<!-- # NZGD2000 -->
<EPSG id="4167"> +proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs  </EPSG>
<!-- # Accra -->
<EPSG id="4168"> +proj=longlat +a=6378300 +b=6356751.689189189 +towgs84=-199,32,322,0,0,0,0 +no_defs  </EPSG>
<!-- # American Samoa 1962 -->
<EPSG id="4169"> +proj=longlat +ellps=clrk66 +towgs84=-115,118,426,0,0,0,0 +no_defs  </EPSG>
<!-- # SIRGAS -->
<EPSG id="4170"> +proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs  </EPSG>
<!-- # RGF93 -->
<EPSG id="4171"> +proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs  </EPSG>
<!-- # POSGAR -->
<EPSG id="4172"> +proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs  </EPSG>
<!-- # IRENET95 -->
<EPSG id="4173"> +proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs  </EPSG>
<!-- # Sierra Leone 1924 -->
<EPSG id="4174"> +proj=longlat +a=6378300 +b=6356751.689189189 +no_defs  </EPSG>
<!-- # Sierra Leone 1968 -->
<EPSG id="4175"> +proj=longlat +ellps=clrk80 +towgs84=-88,4,101,0,0,0,0 +no_defs  </EPSG>
<!-- # Australian Antarctic -->
<EPSG id="4176"> +proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs  </EPSG>
<!-- # Pulkovo 1942(83) -->
<EPSG id="4178"> +proj=longlat +ellps=krass +towgs84=24,-123,-94,0.02,-0.25,-0.13,1.1 +no_defs  </EPSG>
<!-- # Pulkovo 1942(58) -->
<EPSG id="4179"> +proj=longlat +ellps=krass +towgs84=33.4,-146.6,-76.3,-0.359,-0.053,0.844,-0.84 +no_defs  </EPSG>
<!-- # EST97 -->
<EPSG id="4180"> +proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs  </EPSG>
<!-- # Luxembourg 1930 -->
<EPSG id="4181"> +proj=longlat +ellps=intl +towgs84=-193,13.7,-39.3,-0.41,-2.933,2.688,0.43 +no_defs  </EPSG>
<!-- # Azores Occidental 1939 -->
<EPSG id="4182"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # Azores Central 1948 -->
<EPSG id="4183"> +proj=longlat +ellps=intl +towgs84=-104,167,-38,0,0,0,0 +no_defs  </EPSG>
<!-- # Azores Oriental 1940 -->
<EPSG id="4184"> +proj=longlat +ellps=intl +towgs84=-203,141,53,0,0,0,0 +no_defs  </EPSG>
<!-- # Madeira 1936 -->
<EPSG id="4185"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # OSNI 1952 -->
<EPSG id="4188"> +proj=longlat +ellps=airy +towgs84=482.5,-130.6,564.6,-1.042,-0.214,-0.631,8.15 +no_defs  </EPSG>
<!-- # REGVEN -->
<EPSG id="4189"> +proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs  </EPSG>
<!-- # POSGAR 98 -->
<EPSG id="4190"> +proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs  </EPSG>
<!-- # Albanian 1987 -->
<EPSG id="4191"> +proj=longlat +ellps=krass +no_defs  </EPSG>
<!-- # Douala 1948 -->
<EPSG id="4192"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # Manoca 1962 -->
<EPSG id="4193"> +proj=longlat +a=6378249.2 +b=6356515 +towgs84=-70.9,-151.8,-41.4,0,0,0,0 +no_defs  </EPSG>
<!-- # Qornoq 1927 -->
<EPSG id="4194"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # Scoresbysund 1952 -->
<EPSG id="4195"> +proj=longlat +ellps=intl +towgs84=105,326,-102.5,0,0,0.814,-0.6 +no_defs  </EPSG>
<!-- # Ammassalik 1958 -->
<EPSG id="4196"> +proj=longlat +ellps=intl +towgs84=-45,417,-3.5,0,0,0.814,-0.6 +no_defs  </EPSG>
<!-- # Garoua -->
<EPSG id="4197"> +proj=longlat +ellps=clrk80 +no_defs  </EPSG>
<!-- # Kousseri -->
<EPSG id="4198"> +proj=longlat +ellps=clrk80 +no_defs  </EPSG>
<!-- # Egypt 1930 -->
<EPSG id="4199"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # Pulkovo 1995 -->
<EPSG id="4200"> +proj=longlat +ellps=krass +no_defs  </EPSG>
<!-- # Adindan -->
<EPSG id="4201"> +proj=longlat +ellps=clrk80 +no_defs  </EPSG>
<!-- # AGD66 -->
<EPSG id="4202"> +proj=longlat +ellps=aust_SA +no_defs  </EPSG>
<!-- # AGD84 -->
<EPSG id="4203"> +proj=longlat +ellps=aust_SA +no_defs  </EPSG>
<!-- # Ain el Abd -->
<EPSG id="4204"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # Afgooye -->
<EPSG id="4205"> +proj=longlat +ellps=krass +towgs84=-43,-163,45,0,0,0,0 +no_defs  </EPSG>
<!-- # Agadez -->
<EPSG id="4206"> +proj=longlat +a=6378249.2 +b=6356515 +no_defs  </EPSG>
<!-- # Lisbon -->
<EPSG id="4207"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # Aratu -->
<EPSG id="4208"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # Arc 1950 -->
<EPSG id="4209"> +proj=longlat +a=6378249.145 +b=6356514.966398753 +no_defs  </EPSG>
<!-- # Arc 1960 -->
<EPSG id="4210"> +proj=longlat +ellps=clrk80 +no_defs  </EPSG>
<!-- # Batavia -->
<EPSG id="4211"> +proj=longlat +ellps=bessel +no_defs  </EPSG>
<!-- # Barbados 1938 -->
<EPSG id="4212"> +proj=longlat +ellps=clrk80 +no_defs  </EPSG>
<!-- # Beduaram -->
<EPSG id="4213"> +proj=longlat +a=6378249.2 +b=6356515 +no_defs  </EPSG>
<!-- # Beijing 1954 -->
<EPSG id="4214"> +proj=longlat +ellps=krass +no_defs  </EPSG>
<!-- # Belge 1950 -->
<EPSG id="4215"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # Bermuda 1957 -->
<EPSG id="4216"> +proj=longlat +ellps=clrk66 +towgs84=-73,213,296,0,0,0,0 +no_defs  </EPSG>
<!-- # Bogota 1975 -->
<EPSG id="4218"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # Bukit Rimpah -->
<EPSG id="4219"> +proj=longlat +ellps=bessel +towgs84=-384,664,-48,0,0,0,0 +no_defs  </EPSG>
<!-- # Camacupa -->
<EPSG id="4220"> +proj=longlat +ellps=clrk80 +no_defs  </EPSG>
<!-- # Campo Inchauspe -->
<EPSG id="4221"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # Cape -->
<EPSG id="4222"> +proj=longlat +a=6378249.145 +b=6356514.966398753 +no_defs  </EPSG>
<!-- # Carthage -->
<EPSG id="4223"> +proj=longlat +a=6378249.2 +b=6356515 +no_defs  </EPSG>
<!-- # Chua -->
<EPSG id="4224"> +proj=longlat +ellps=intl +towgs84=-134,229,-29,0,0,0,0 +no_defs  </EPSG>
<!-- # Corrego Alegre -->
<EPSG id="4225"> +proj=longlat +ellps=intl +towgs84=-206,172,-6,0,0,0,0 +no_defs  </EPSG>
<!-- # Cote d'Ivoire -->
<EPSG id="4226"> +proj=longlat +a=6378249.2 +b=6356515 +no_defs  </EPSG>
<!-- # Deir ez Zor -->
<EPSG id="4227"> +proj=longlat +a=6378249.2 +b=6356515 +no_defs  </EPSG>
<!-- # Douala -->
<EPSG id="4228"> +proj=longlat +a=6378249.2 +b=6356515 +no_defs  </EPSG>
<!-- # Egypt 1907 -->
<EPSG id="4229"> +proj=longlat +ellps=helmert +no_defs  </EPSG>
<!-- # ED50 -->
<EPSG id="4230"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # ED87 -->
<EPSG id="4231"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # Fahud -->
<EPSG id="4232"> +proj=longlat +ellps=clrk80 +no_defs  </EPSG>
<!-- # Gandajika 1970 -->
<EPSG id="4233"> +proj=longlat +ellps=intl +towgs84=-133,-321,50,0,0,0,0 +no_defs  </EPSG>
<!-- # Garoua -->
<EPSG id="4234"> +proj=longlat +a=6378249.2 +b=6356515 +no_defs  </EPSG>
<!-- # Guyane Francaise -->
<EPSG id="4235"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # Hu Tzu Shan -->
<EPSG id="4236"> +proj=longlat +ellps=intl +towgs84=-637,-549,-203,0,0,0,0 +no_defs  </EPSG>
<!-- # HD72 -->
<EPSG id="4237"> +proj=longlat +ellps=GRS67 +no_defs  </EPSG>
<!-- # ID74 -->
<EPSG id="4238"> +proj=longlat +a=6378160 +b=6356774.50408554 +no_defs  </EPSG>
<!-- # Indian 1954 -->
<EPSG id="4239"> +proj=longlat +a=6377276.345 +b=6356075.413140239 +towgs84=217,823,299,0,0,0,0 +no_defs  </EPSG>
<!-- # Indian 1975 -->
<EPSG id="4240"> +proj=longlat +a=6377276.345 +b=6356075.413140239 +no_defs  </EPSG>
<!-- # Jamaica 1875 -->
<EPSG id="4241"> +proj=longlat +ellps=clrk80 +no_defs  </EPSG>
<!-- # JAD69 -->
<EPSG id="4242"> +proj=longlat +ellps=clrk66 +no_defs  </EPSG>
<!-- # Kalianpur 1880 -->
<EPSG id="4243"> +proj=longlat +a=6377299.36559538 +b=6356098.357204817 +no_defs  </EPSG>
<!-- # Kandawala -->
<EPSG id="4244"> +proj=longlat +a=6377276.345 +b=6356075.413140239 +towgs84=-97,787,86,0,0,0,0 +no_defs  </EPSG>
<!-- # Kertau -->
<EPSG id="4245"> +proj=longlat +a=6377304.063 +b=6356103.038993155 +towgs84=-11,851,5,0,0,0,0 +no_defs  </EPSG>
<!-- # KOC -->
<EPSG id="4246"> +proj=longlat +ellps=clrk80 +no_defs  </EPSG>
<!-- # La Canoa -->
<EPSG id="4247"> +proj=longlat +ellps=intl +towgs84=-273.5,110.6,-357.9,0,0,0,0 +no_defs  </EPSG>
<!-- # PSAD56 -->
<EPSG id="4248"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # Lake -->
<EPSG id="4249"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # Leigon -->
<EPSG id="4250"> +proj=longlat +ellps=clrk80 +towgs84=-130,29,364,0,0,0,0 +no_defs  </EPSG>
<!-- # Liberia 1964 -->
<EPSG id="4251"> +proj=longlat +ellps=clrk80 +towgs84=-90,40,88,0,0,0,0 +no_defs  </EPSG>
<!-- # Lome -->
<EPSG id="4252"> +proj=longlat +a=6378249.2 +b=6356515 +no_defs  </EPSG>
<!-- # Luzon 1911 -->
<EPSG id="4253"> +proj=longlat +ellps=clrk66 +no_defs  </EPSG>
<!-- # Hito XVIII 1963 -->
<EPSG id="4254"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # Herat North -->
<EPSG id="4255"> +proj=longlat +ellps=intl +towgs84=-333,-222,114,0,0,0,0 +no_defs  </EPSG>
<!-- # Mahe 1971 -->
<EPSG id="4256"> +proj=longlat +ellps=clrk80 +towgs84=41,-220,-134,0,0,0,0 +no_defs  </EPSG>
<!-- # Makassar -->
<EPSG id="4257"> +proj=longlat +ellps=bessel +towgs84=-587.8,519.75,145.76,0,0,0,0 +no_defs  </EPSG>
<!-- # ETRS89 -->
<EPSG id="4258"> +proj=longlat +ellps=GRS80 +no_defs  </EPSG>
<!-- # Malongo 1987 -->
<EPSG id="4259"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # Manoca -->
<EPSG id="4260"> +proj=longlat +ellps=clrk80 +towgs84=-70.9,-151.8,-41.4,0,0,0,0 +no_defs  </EPSG>
<!-- # Merchich -->
<EPSG id="4261"> +proj=longlat +a=6378249.2 +b=6356515 +towgs84=31,146,47,0,0,0,0 +no_defs  </EPSG>
<!-- # Massawa -->
<EPSG id="4262"> +proj=longlat +ellps=bessel +towgs84=639,405,60,0,0,0,0 +no_defs  </EPSG>
<!-- # Minna -->
<EPSG id="4263"> +proj=longlat +ellps=clrk80 +no_defs  </EPSG>
<!-- # Mhast -->
<EPSG id="4264"> +proj=longlat +ellps=intl +towgs84=-252.95,-4.11,-96.38,0,0,0,0 +no_defs  </EPSG>
<!-- # Monte Mario -->
<EPSG id="4265"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # M'poraloko -->
<EPSG id="4266"> +proj=longlat +a=6378249.2 +b=6356515 +no_defs  </EPSG>
<!-- # NAD27 -->
<EPSG id="4267"> +proj=longlat +ellps=clrk66 +datum=NAD27 +no_defs  </EPSG>
<!-- # NAD27 Michigan -->
<EPSG id="4268"> +proj=longlat +a=6378450.047548896 +b=6356826.621488444 +no_defs  </EPSG>
<!-- # NAD83 -->
<EPSG id="4269"> +proj=longlat +ellps=GRS80 +datum=NAD83 +no_defs  </EPSG>
<!-- # Nahrwan 1967 -->
<EPSG id="4270"> +proj=longlat +ellps=clrk80 +no_defs  </EPSG>
<!-- # Naparima 1972 -->
<EPSG id="4271"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # NZGD49 -->
<EPSG id="4272"> +proj=longlat +ellps=intl +datum=nzgd49 +no_defs  </EPSG>
<!-- # NGO 1948 -->
<EPSG id="4273"> +proj=longlat +a=6377492.018 +b=6356173.508712696 +towgs84=278.3,93,474.5,7.889,0.05,-6.61,6.21 +no_defs  </EPSG>
<!-- # Datum 73 -->
<EPSG id="4274"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # NTF -->
<EPSG id="4275"> +proj=longlat +a=6378249.2 +b=6356515 +towgs84=-168,-60,320,0,0,0,0 +no_defs  </EPSG>
<!-- # NSWC 9Z-2 -->
<EPSG id="4276"> +proj=longlat +ellps=WGS66 +no_defs  </EPSG>
<!-- # OSGB 1936 -->
<EPSG id="4277"> +proj=longlat +ellps=airy +no_defs  </EPSG>
<!-- # OSGB70 -->
<EPSG id="4278"> +proj=longlat +ellps=airy +no_defs  </EPSG>
<!-- # OS(SN)80 -->
<EPSG id="4279"> +proj=longlat +ellps=airy +no_defs  </EPSG>
<!-- # Padang -->
<EPSG id="4280"> +proj=longlat +ellps=bessel +no_defs  </EPSG>
<!-- # Palestine 1923 -->
<EPSG id="4281"> +proj=longlat +a=6378300.789 +b=6356566.435 +no_defs  </EPSG>
<!-- # Pointe Noire -->
<EPSG id="4282"> +proj=longlat +a=6378249.2 +b=6356515 +no_defs  </EPSG>
<!-- # GDA94 -->
<EPSG id="4283"> +proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs  </EPSG>
<!-- # Pulkovo 1942 -->
<EPSG id="4284"> +proj=longlat +ellps=krass +no_defs  </EPSG>
<!-- # Qatar 1974 -->
<EPSG id="4285"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # Qatar 1948 -->
<EPSG id="4286"> +proj=longlat +ellps=helmert +no_defs  </EPSG>
<!-- # Qornoq -->
<EPSG id="4287"> +proj=longlat +ellps=intl +towgs84=164,138,-189,0,0,0,0 +no_defs  </EPSG>
<!-- # Loma Quintana -->
<EPSG id="4288"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # Amersfoort -->
<EPSG id="4289"> +proj=longlat +ellps=bessel +no_defs  </EPSG>
<!-- # SAD69 -->
<EPSG id="4291"> +proj=longlat +ellps=GRS67 +no_defs  </EPSG>
<!-- # Sapper Hill 1943 -->
<EPSG id="4292"> +proj=longlat +ellps=intl +towgs84=-355,21,72,0,0,0,0 +no_defs  </EPSG>
<!-- # Schwarzeck -->
<EPSG id="4293"> +proj=longlat +ellps=bess_nam +no_defs  </EPSG>
<!-- # Segora -->
<EPSG id="4294"> +proj=longlat +ellps=bessel +no_defs  </EPSG>
<!-- # Serindung -->
<EPSG id="4295"> +proj=longlat +ellps=bessel +no_defs  </EPSG>
<!-- # Sudan -->
<EPSG id="4296"> +proj=longlat +a=6378249.2 +b=6356515 +no_defs  </EPSG>
<!-- # Tananarive -->
<EPSG id="4297"> +proj=longlat +ellps=intl +towgs84=-189,-242,-91,0,0,0,0 +no_defs  </EPSG>
<!-- # Timbalai 1948 -->
<EPSG id="4298"> +proj=longlat +ellps=evrstSS +no_defs  </EPSG>
<!-- # TM65 -->
<EPSG id="4299"> +proj=longlat +a=6377340.189 +b=6356034.447938534 +no_defs  </EPSG>
<!-- # TM75 -->
<EPSG id="4300"> +proj=longlat +a=6377340.189 +b=6356034.447938534 +no_defs  </EPSG>
<!-- # Tokyo -->
<EPSG id="4301"> +proj=longlat +ellps=bessel +no_defs  </EPSG>
<!-- # Trinidad 1903 -->
<EPSG id="4302"> +proj=longlat +a=6378293.63683822 +b=6356617.979337744 +towgs84=-61.702,284.488,472.052,0,0,0,0 +no_defs  </EPSG>
<!-- # TC(1948) -->
<EPSG id="4303"> +proj=longlat +ellps=helmert +no_defs  </EPSG>
<!-- # Voirol 1875 -->
<EPSG id="4304"> +proj=longlat +a=6378249.2 +b=6356515 +towgs84=-73,-247,227,0,0,0,0 +no_defs  </EPSG>
<!-- # Bern 1938 -->
<EPSG id="4306"> +proj=longlat +ellps=bessel +no_defs  </EPSG>
<!-- # Nord Sahara 1959 -->
<EPSG id="4307"> +proj=longlat +ellps=clrk80 +no_defs  </EPSG>
<!-- # RT38 -->
<EPSG id="4308"> +proj=longlat +ellps=bessel +no_defs  </EPSG>
<!-- # Yacare -->
<EPSG id="4309"> +proj=longlat +ellps=intl +towgs84=-155,171,37,0,0,0,0 +no_defs  </EPSG>
<!-- # Yoff -->
<EPSG id="4310"> +proj=longlat +a=6378249.2 +b=6356515 +no_defs  </EPSG>
<!-- # Zanderij -->
<EPSG id="4311"> +proj=longlat +ellps=intl +towgs84=-265,120,-358,0,0,0,0 +no_defs  </EPSG>
<!-- # MGI -->
<EPSG id="4312"> +proj=longlat +ellps=bessel +no_defs  </EPSG>
<!-- # Belge 1972 -->
<EPSG id="4313"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # DHDN -->
<EPSG id="4314"> +proj=longlat +ellps=bessel +datum=potsdam +no_defs  </EPSG>
<!-- # Conakry 1905 -->
<EPSG id="4315"> +proj=longlat +a=6378249.2 +b=6356515 +towgs84=-23,259,-9,0,0,0,0 +no_defs  </EPSG>
<!-- # Dealul Piscului 1933 -->
<EPSG id="4316"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # Dealul Piscului 1970 -->
<EPSG id="4317"> +proj=longlat +ellps=krass +no_defs  </EPSG>
<!-- # NGN -->
<EPSG id="4318"> +proj=longlat +ellps=WGS84 +no_defs  </EPSG>
<!-- # KUDAMS -->
<EPSG id="4319"> +proj=longlat +ellps=GRS80 +no_defs  </EPSG>
<!-- # WGS 72 -->
<EPSG id="4322"> +proj=longlat +ellps=WGS72 +no_defs  </EPSG>
<!-- # WGS 72BE -->
<EPSG id="4324"> +proj=longlat +ellps=WGS72 +towgs84=0,0,1.9,0,0,0.814,-0.38 +no_defs  </EPSG>
<!-- # WGS 84 -->
<EPSG id="4326"> +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs  </EPSG>
<!-- # Anguilla 1957 -->
<EPSG id="4600"> +proj=longlat +ellps=clrk80 +no_defs  </EPSG>
<!-- # Antigua 1943 -->
<EPSG id="4601"> +proj=longlat +ellps=clrk80 +towgs84=-255,-15,71,0,0,0,0 +no_defs  </EPSG>
<!-- # Dominica 1945 -->
<EPSG id="4602"> +proj=longlat +ellps=clrk80 +towgs84=725,685,536,0,0,0,0 +no_defs  </EPSG>
<!-- # Grenada 1953 -->
<EPSG id="4603"> +proj=longlat +ellps=clrk80 +towgs84=72,213.7,93,0,0,0,0 +no_defs  </EPSG>
<!-- # Montserrat 1958 -->
<EPSG id="4604"> +proj=longlat +ellps=clrk80 +towgs84=174,359,365,0,0,0,0 +no_defs  </EPSG>
<!-- # St. Kitts 1955 -->
<EPSG id="4605"> +proj=longlat +ellps=clrk80 +towgs84=9,183,236,0,0,0,0 +no_defs  </EPSG>
<!-- # St. Lucia 1955 -->
<EPSG id="4606"> +proj=longlat +ellps=clrk80 +towgs84=-149,128,296,0,0,0,0 +no_defs  </EPSG>
<!-- # St. Vincent 1945 -->
<EPSG id="4607"> +proj=longlat +ellps=clrk80 +towgs84=195.671,332.517,274.607,0,0,0,0 +no_defs  </EPSG>
<!-- # NAD27(76) -->
<EPSG id="4608"> +proj=longlat +ellps=clrk66 +no_defs  </EPSG>
<!-- # NAD27(CGQ77) -->
<EPSG id="4609"> +proj=longlat +ellps=clrk66 +no_defs  </EPSG>
<!-- # Xian 1980 -->
<EPSG id="4610"> +proj=longlat +a=6378140 +b=6356755.288157528 +no_defs  </EPSG>
<!-- # Hong Kong 1980 -->
<EPSG id="4611"> +proj=longlat +ellps=intl +towgs84=-162.619,-276.959,-161.764,0.067753,-2.24365,-1.15883,-1.09425 +no_defs  </EPSG>
<!-- # JGD2000 -->
<EPSG id="4612"> +proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs  </EPSG>
<!-- # Segara -->
<EPSG id="4613"> +proj=longlat +ellps=bessel +no_defs  </EPSG>
<!-- # QND95 -->
<EPSG id="4614"> +proj=longlat +ellps=intl +towgs84=-119.425,-303.659,-11.0006,1.1643,0.174458,1.09626,3.65706 +no_defs  </EPSG>
<!-- # Porto Santo -->
<EPSG id="4615"> +proj=longlat +ellps=intl +towgs84=-499,-249,314,0,0,0,0 +no_defs  </EPSG>
<!-- # Selvagem Grande -->
<EPSG id="4616"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # NAD83(CSRS) -->
<EPSG id="4617"> +proj=longlat +ellps=GRS80 +no_defs  </EPSG>
<!-- # SAD69 -->
<EPSG id="4618"> +proj=longlat +ellps=aust_SA +no_defs  </EPSG>
<!-- # SWEREF99 -->
<EPSG id="4619"> +proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs  </EPSG>
<!-- # Point 58 -->
<EPSG id="4620"> +proj=longlat +ellps=clrk80 +towgs84=-106,-129,165,0,0,0,0 +no_defs  </EPSG>
<!-- # Fort Marigot -->
<EPSG id="4621"> +proj=longlat +ellps=intl +towgs84=137,248,-430,0,0,0,0 +no_defs  </EPSG>
<!-- # Sainte Anne -->
<EPSG id="4622"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # CSG67 -->
<EPSG id="4623"> +proj=longlat +ellps=intl +towgs84=-186,230,110,0,0,0,0 +no_defs  </EPSG>
<!-- # RGFG95 -->
<EPSG id="4624"> +proj=longlat +ellps=GRS80 +towgs84=2,2,-2,0,0,0,0 +no_defs  </EPSG>
<!-- # Fort Desaix -->
<EPSG id="4625"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # Piton des Neiges -->
<EPSG id="4626"> +proj=longlat +ellps=intl +towgs84=94,-948,-1292,0,0,0,0 +no_defs  </EPSG>
<!-- # RGR92 -->
<EPSG id="4627"> +proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs  </EPSG>
<!-- # Tahiti -->
<EPSG id="4628"> +proj=longlat +ellps=intl +towgs84=162,117,154,0,0,0,0 +no_defs  </EPSG>
<!-- # Tahaa -->
<EPSG id="4629"> +proj=longlat +ellps=intl +towgs84=65,342,77,0,0,0,0 +no_defs  </EPSG>
<!-- # IGN72 Nuku Hiva -->
<EPSG id="4630"> +proj=longlat +ellps=intl +towgs84=84,274,65,0,0,0,0 +no_defs  </EPSG>
<!-- # K0 1949 -->
<EPSG id="4631"> +proj=longlat +ellps=intl +towgs84=145,-187,103,0,0,0,0 +no_defs  </EPSG>
<!-- # Combani 1950 -->
<EPSG id="4632"> +proj=longlat +ellps=intl +towgs84=-382,-59,-262,0,0,0,0 +no_defs  </EPSG>
<!-- # IGN56 Lifou -->
<EPSG id="4633"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # IGN72 Grand Terre -->
<EPSG id="4634"> +proj=longlat +ellps=intl +no_defs  </EPSG>
<!-- # ST87 Ouvea -->
<EPSG id="4635"> +proj=longlat +ellps=intl +towgs84=-122.383,-188.696,103.344,3.5107,-4.9668,-5.7047,4.4798 +no_defs  </EPSG>
<!-- # Petrels 1972 -->
<EPSG id="4636"> +proj=longlat +ellps=intl +towgs84=365,194,166,0,0,0,0 +no_defs  </EPSG>
<!-- # Perroud 1950 -->
<EPSG id="4637"> +proj=longlat +ellps=intl +towgs84=325,154,172,0,0,0,0 +no_defs  </EPSG>
<!-- # Saint Pierre et Miquelon 1950 -->
<EPSG id="4638"> +proj=longlat +ellps=clrk66 +towgs84=30,430,368,0,0,0,0 +no_defs  </EPSG>
<!-- # MOP78 -->
<EPSG id="4639"> +proj=longlat +ellps=intl +towgs84=252,-132,-125,0,0,0,0 +no_defs  </EPSG>
<!-- # RRAF 1991 -->
<EPSG id="4640"> +proj=longlat +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +no_defs  </EPSG>
<!-- # IGN53 Mare -->
<EPSG id="4641"> +proj=longlat +ellps=intl +towgs84=-408.809,366.856,-412.987,1.8842,-0.5308,2.1655,-121.099 +no_defs  </EPSG>
<!-- # ST84 Ile des Pins -->
<EPSG id="4642"> +proj=longlat +ellps=intl +towgs84=244.416,85.339,168.114,-8.9353,7.7523,12.5953,14.268 +no_defs  </EPSG>
<!-- # ST71 Belep -->